# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-01 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('user_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('user_pwd', models.CharField(max_length=40)),
            ],
        ),
    ]
